### ISSUE TITLE
NameError: global name 'pad_step_embedded' is not defined

### ISSUE THREAD

**Issue by SeekPoint** [HarryWuxh/Attention_Based_RNN_for_Intent_Detetaction_and_Slot_Filling#3]
ub16hp@UB16HP:~/ub16_prj/Attention_Based_RNN_for_Intent_Detetaction_and_Slot_Filling$ python main.py 
4478 4478 4478
500 500 500
(['i', 'want', 'to', 'fly', 'from', 'baltimore', 'to', 'dallas', 'round', 'trip', '<EOS>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'], ['O', 'O', 'O', 'O', 'O', 'B-fromloc.city_name', 'O', 'B-toloc.city_name', 'B-round_trip', 'I-round_trip', '<EOS>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'], 'atis_flight')
([631, 167, 18, 829, 114, 530, 18, 401, 49, 834, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 10, [2, 2, 2, 2, 2, 84, 2, 95, 90, 111, 45, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 21)
atis_flight
871 123 22
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    model.build()
  File "/home/ub16hp/ub16_prj/Attention_Based_RNN_for_Intent_Detetaction_and_Slot_Filling/model.py", line 115, in build
    decoder_outputs, _, _ = tf.contrib.seq2seq.dynamic_decode(decoder=decoder, output_time_major=True, impute_finished=True, maximum_iterations=self.input_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 286, in dynamic_decode
    swap_memory=swap_memory)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2816, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2640, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2590, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 234, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/seq2seq/python/ops/basic_decoder.py", line 147, in step
    sample_ids=sample_ids)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/seq2seq/python/ops/helper.py", line 163, in next_inputs
    time=time, outputs=outputs, state=state, sample_ids=sample_ids)
  File "/home/ub16hp/ub16_prj/Attention_Based_RNN_for_Intent_Detetaction_and_Slot_Filling/model.py", line 100, in next_input_fn
    next_inputs = tf.cond(all_finished, lambda: pad_step_embedded, lambda: next_inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 316, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1855, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1725, in BuildCondBranch
    original_result = fn()
  File "/home/ub16hp/ub16_prj/Attention_Based_RNN_for_Intent_Detetaction_and_Slot_Filling/model.py", line 100, in <lambda>
    next_inputs = tf.cond(all_finished, lambda: pad_step_embedded, lambda: next_inputs)
NameError: global name 'pad_step_embedded' is not defined
ub16hp@UB16HP:~/ub16_prj/Attention_Based_RNN_for_Intent_Detetaction_and_Slot_Filling$

**Comment by HarryWuxh** [comment]
Thx for the issue. The problem has been fixed.
